version: '3.8'
services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    environment:
      - TZ:=${POSTGRES_ITMEZONE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./test/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db:
    driver: local
