name: CI

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: './docker-compose-e2e-test.yml'
          down-flags: '--volumes'
          services: db
        env:
          POSTGRES_USERNAME: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DATABASE: 'postgres'
          POSTGRES_HOST: 'localhost'
          POSTGRES_TIMEZONE: 'Asia/Singapore'
      - name: Run script file
        run: |
          chmod +x ./test/e2e_test.sh
          ./test/e2e_test.sh
        shell: bash
        env:
          POSTGRES_USERNAME: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DATABASE: 'postgres'
          POSTGRES_HOST: 'localhost'
          INIT_INDEXER: true
